version: '3.9'

services:
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=searchEngineDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/data

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: celery -A crawler worker --loglevel=info
    volumes: 
      - .:/search_engine
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - redis

volumes: 
  database: