version: '3.9'

services:
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=searchEngineDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - database:/data

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    volumes: 
      - ./app:/app
    command: celery -A crawler worker --loglevel=info
    
volumes: 
  database: