version: '3.9'

services:
  postgres:
    image: postgres:14.4
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=searchEngineDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    
  app:
    build: .
    command: bash -c "
      python manage.py migrate &&
      celery -A src.crawler worker --detach  &&
      python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/search_engine
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - redis